# Generated by Django 4.2.29 on 2026-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Developer', 'Developer'), ('Moderator', 'Moderator'), ('Verified User', 'Verified User'), ('General User', 'General User')], default='General User', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
