# Generated by Django 4.2.29 on 2026-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_platformuser_password_hash_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='supabase_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
