# Generated by Django 4.2.29 on 2026-04-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_topic_created_idx_post_post_created_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_topic_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_deleted_created_idx',
        ),
    ]
