# Generated by Django 4.2.29 on 2026-04-08 15:32

from django.db import migrations, models
import json


def set_default_references(apps, schema_editor):
	"""Set all existing posts to have scholr.com as default reference."""
	Post = apps.get_model('posts', 'Post')
	default_refs = json.dumps([{'title': 'Reference', 'url': 'https://scholr.com'}])
	Post.objects.all().update(references=default_refs)


def revert_references(apps, schema_editor):
	"""Revert references to empty JSON array."""
	Post = apps.get_model('posts', 'Post')
	Post.objects.all().update(references='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_ai',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='references',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.RunPython(set_default_references, revert_references),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_ai', '-created_at'], name='posts_is_ai_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_ai', 'content_type', '-created_at'], name='posts_is_ai_ct_created_idx'),
        ),
    ]
