# Generated by Django 4.2.29 on 2026-04-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_commentvote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commentvote',
            new_name='interaction_comment_5d7367_idx',
            old_name='commentvote_comment_idx',
        ),
    ]
